### ISSUE TITLE
Mini rebrand `myst-tools.org` --> `mystmd.org`

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/team-compass#21]
This is following up on conversations from the last month around branding of [myst-tools.org](http://myst-tools.org/) that @choldgraf started at JupyterCon. @choldgraf proposed to move the website and social media to [mystmd.org](http://mystmd.org/), this issue is tracking progress following through on that choice!

> The thinking on this is that it (1) is easier to say/spell/talk about the URL (myst-dash-tools-dot-org vs myst-M-D-dot-org); (2) is not tied to a programming language (e.g. mystjs). The one challenge is that it might be "just" markdown, @choldgraf gave an example of Obsidian (note-taking tool) using this branding pattern and it being successful for them.

Some of the outstanding tasks:

- [x] Twitter
- [x] Mastodon
- [x] MEP
- [x] All urls map through correctly
- [x] myst-spec.readthedocs.org
- [x] https://github.com/executablebooks/mystjs/pull/427
- [x] https://github.com/executablebooks/team-compass/pull/20
- [x] https://github.com/executablebooks/myst-enhancement-proposals/pull/21
- [x] https://github.com/executablebooks/meta/pull/1031
- [x] https://github.com/executablebooks/jupyterlab-myst/pull/156
- [x] https://github.com/myst-templates/templates/pull/29
- [x] https://github.com/executablebooks/thebe/pull/636
- [x] https://github.com/executablebooks/.github/pull/30
- [x] https://github.com/executablebooks/myst-theme/pull/127
- [x] https://github.com/executablebooks/thebe/issues/590

I will continue adding a few PRs around the place to point to the new domain.

**Comment by choldgraf** [comment]
I've merged the PRs opened above!

**Comment by chrisjsewell** [comment]
Heya, invited you as maintainer

**Comment by choldgraf** [comment]
Nice, thanks - I added @rowanc1 as well

**Comment by rowanc1** [comment]
🚀 that is now forwarding, thanks!
